// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXqUme6SVWB4g9q15AtC9xz7aXavYEzLE',
    appId: '1:854716496772:web:6318d517660fe012603bd1',
    messagingSenderId: '854716496772',
    projectId: 'myeiksagar-c1009',
    authDomain: 'myeiksagar-c1009.firebaseapp.com',
    storageBucket: 'myeiksagar-c1009.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd84UQRPbmwbY4IeUTFSx24XWXaF6zdfE',
    appId: '1:854716496772:android:0c9580ee7c2c8e1a603bd1',
    messagingSenderId: '854716496772',
    projectId: 'myeiksagar-c1009',
    storageBucket: 'myeiksagar-c1009.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9pSj8Ri181zSYdV4d3Bx9l9VtiS3fChs',
    appId: '1:854716496772:ios:d3d6b701d8501dcd603bd1',
    messagingSenderId: '854716496772',
    projectId: 'myeiksagar-c1009',
    storageBucket: 'myeiksagar-c1009.appspot.com',
    iosBundleId: 'com.example.helper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9pSj8Ri181zSYdV4d3Bx9l9VtiS3fChs',
    appId: '1:854716496772:ios:a3afa473ab12ebf2603bd1',
    messagingSenderId: '854716496772',
    projectId: 'myeiksagar-c1009',
    storageBucket: 'myeiksagar-c1009.appspot.com',
    iosBundleId: 'com.example.helper.RunnerTests',
  );
}
